1.0.3 release
soos-io/soos-sca-teamcity-plugin pull request #4
Opened 2022-01-10 16:54 UTC by SOOS-MFuhr

- fixed async mode in SoosSCAService class
- changed the way of showing the reportStatusUrl in SoosSCA class
- added reportStatusUrl field in editParameters.jsp

2022-01-12 13:52 UTC, SOOS-ABenassi requested changes
@SOOS-MFuhr see my comment

2022-01-12 13:52 UTC, SOOS-ABenassi commented on soos-sca-agent/src/main/java/io/soos/SoosSCAService.java
> +        return scriptContent;
@SOOS-MFuhr maybe here we could use a switch-case structure instead of if-else. It will help to make the code more readable

2022-01-13 18:34 UTC, SOOS-MFuhr commented on soos-sca-agent/src/main/java/io/soos/SoosSCAService.java
> +        return scriptContent;
done!

2022-01-18 14:30 UTC, SOOS-ABenassi reviewed
See my comment

2022-01-18 14:30 UTC, SOOS-ABenassi commented on build/pom.xml
> +    <version>1.0.3</version>
@SOOS-MFuhr you could define a property called `<sca.version>1.0.3</sca.version>` and use it instead of having the string `1.0.3` several times
https://maven.apache.org/pom.html#Properties

2022-03-11 13:25 UTC, SOOS-JAlvarez commented
@SOOS-ABenassi closing this, will be overwrited with release 1.1.0

2022-03-11 13:25 UTC, closed without merging