Friendly report
soos-io/soos-sca-teamcity-plugin pull request #5
Opened 2022-01-20 19:05 UTC by SOOS-MFuhr

- add ResultFilePathBuilder class for creating the path where to create de artifact for saving the result URL
- refactor some methods from SoosSCAService to Utils class
- create soosReport.jsp for showing images and view report button
- change version in the pom files

2022-02-01 12:49 UTC, SOOS-ABenassi requested changes
@SOOS-MFuhr See my comments

2022-02-01 12:49 UTC, SOOS-ABenassi commented on soos-sca-agent/src/main/java/io/soos/SoosSCAService.java
> +                    LOG.info("Scan analysis finished successfully. To see the results go to: " + result);
@SOOS-MFuhr in the same way that you did in line 81, you can use `{}` here too instead of +

2022-02-01 12:49 UTC, SOOS-ABenassi commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +                        && line.contains(PluginConstants.SOOS_IMAGES_PRODUCTION_CDN)) {
@SOOS-MFuhr here you could simplify the three `&&` condition, creating an array with the constants and making this: `contantsConditions.stream().anyMatch(line::contains)`

2022-02-01 12:49 UTC, SOOS-ABenassi commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +                } else if ( !firstChar.equals("#") && line.contains(PluginConstants.CONTENT_POLICY_PROPERTY)
@SOOS-MFuhr part of this condition is the same that line 44. We should try to simplify this logic

2022-02-01 12:49 UTC, SOOS-ABenassi commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +            reader = new Scanner(teamcityStartupPropertiesFile);
@SOOS-MFuhr the reader is used only inside the try-catch block so we could move line 90 to line 92

2022-02-01 12:49 UTC, SOOS-ABenassi commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +    }
@SOOS-MFuhr this method could be refactored. The only argument that changes if the OS is windows is `PluginConstants.WIN_SCRIPT_EXT` or `PluginConstants.UNIX_SCRIPT_EXT` so we could join the most of the code, for example: `return File.createTempFile(PluginConstants.CUSTOM_SCRIPT, OS_EXT, teamcityContext.getAgentTempDirectory());`

2022-02-01 12:49 UTC, SOOS-ABenassi commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +                .append(" ")
@SOOS-MFuhr could you define constants for `" "` and `\n` and use them?

2022-02-03 14:13 UTC, SOOS-MFuhr commented on soos-sca-agent/src/main/java/io/soos/SoosSCAService.java
> +                    LOG.info("Scan analysis finished successfully. To see the results go to: " + result);
done! replace with concat()

2022-02-03 14:18 UTC, SOOS-MFuhr commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +                        && line.contains(PluginConstants.SOOS_IMAGES_PRODUCTION_CDN)) {
great! thanks!

2022-02-04 14:01 UTC, SOOS-MFuhr commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +            reader = new Scanner(teamcityStartupPropertiesFile);
yes, done!

2022-02-04 14:01 UTC, SOOS-MFuhr commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +    }
done!

2022-02-04 14:06 UTC, SOOS-MFuhr commented on soos-sca-agent/src/main/java/io/soos/utils/Utils.java
> +                .append(" ")
done

2022-03-11 13:18 UTC, merged